### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by seghier** [torinos-yt/VL.Alembic#2] opened 2023-07-07 22:37 UTC
Is there any example how to read alembic file?

**Comment by seghier** [comment] 2023-07-10 07:05
After many tests, this is a nightmare. Tons of libraries, and finally, it didn't work!

**Comment by torinos-yt** [comment] 2023-07-10 07:12
See the `HowTo Read Alembic Archive` help patch. However, we have to use 2021.4.x because until recently we have not had the time to support the current gamma 5.x. Support for gamma 5.x will be released by the end of this month.

**Comment by torinos-yt** [comment] 2023-07-11 05:22
I have for the moment confirmed that the latest VL.Alembic 0.1.5 works fine with gamma 5.2.

If it does not work with 0.1.5, it may contain data in a format that is not expected. Feel free to reopen the issue if the problem not resolved.

**Closed as completed by torinos-yt** 2023-07-11 05:22 UTC
